models.py
"""All database models are located here"""
from flask.ext.login import UserMixin
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    social_id = db.Column(db.String(64), nullable=False, unique=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)


    def __init__(self, username, email, social_id):
        self.username = username
        self.email = email
        self.social_id = social_id

    def __repr__(self):
        return '<User %r>' % self.username


class Animal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    text = db.Column(db.Text)
    url = db.Column(db.String(264))
    picture_url = db.Column(db.String(264))
    summary = db.Column(db.Text)

    def __init__(self, name, text, url, picture_url, summary=''):
        self.name = name
        self.text = text
        self.url = url
        self.picture_url = picture_url
        self.summary = summary

    def __repr__(self):
        return '<Animal %r>' % self.name

app.py
"""Configuration of the application lives here"""
import os
from flask import Flask
from flask.ext.login import LoginManager, UserMixin
from models import db, User
from views import blueprint


STAGE = os.getenv('FLASK_CONFIGURATION_SETTINGS', 'production')

app = Flask(__name__)
app.register_blueprint(blueprint)

app.config.from_object('config.FinalConfig')

db.init_app(app)
lm = LoginManager(app)

@lm.user_loader
def load_user(id):
    return User.query.get(int(id))


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)

views.py
"""All the views for the site are included here"""
from flask import Blueprint, url_for, request, render_template, redirect, flash
from flask.ext.login import LoginManager, login_user, logout_user, \
    current_user
from sqlalchemy import func
from models import db, User, Animal
from oauth import OAuthSignIn

blueprint = Blueprint('views', __name__)


@blueprint.route('/')
def index():
    if current_user.is_anonymous():
        return render_template('index.html')
    return render_template('search_home.html')


@blueprint.route('/search')
def search():
    if current_user.is_anonymous():
        return redirect(url_for('views.index'))
    keywords = request.args.get('query')
    if not keywords:
        return render_template('search.html', animals={}, keywords=keywords)
    query = keywords.split(' ')
    animals = Animal.query.filter(Animal.name.ilike("%" + func.lower(query.pop()) + "%"))
    while query:
        animals = animals.union(Animal.query.filter(Animal.name.ilike("%" + func.lower(query.pop()) + "%")))
    print(query)
    return render_template('search.html', animals=animals, keywords=keywords)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.index'))


@blueprint.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('views.index'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@blueprint.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('views.index'))
    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash('Authentication failed.')
        return redirect(url_for('views.index'))
    user = User.query.filter_by(social_id=social_id).first()
    if not user:
        user = User(social_id=social_id, username=username, email=email)
        db.session.add(user)
        db.session.commit()
    login_user(user, True)
    return redirect(url_for('views.index'))

templates/base.html
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Oz Content test search</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='foundation.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static',filename='app.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static',filename='foundation-icons.css') }}" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <script src="{{ url_for('static',filename='modernizr.js') }}"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-62973120-1', 'auto');
      ga('send', 'pageview');

  </script>
  </head>
  <body>
    
    {% block content %}    
    {% endblock content %}
    
    <script src="{{ url_for('static', filename='jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation.min.js') }}"></script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row center-div">
      <div class="large-8 large-offset-2 large-centered columns end">
        <div class="row text-center">
          <h1>Welcome to Oz Zoo Search!</h1>
          <div class="large-12 large-centered columns">
            <a role="button" href="{{ url_for('views.oauth_authorize', provider='twitter') }}" class="webicon twitter button"> <i class="fi-social-twitter"></i> Login with Twitter</a>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% block content %}
    <div class="row center-div">
      <div class="large-8 large-offset-2 large-centered medium-8 medium-offset-2 small-10 small-offset-1 columns end">
        <div class="row text-center">
          <h1>Oz Zoo Search!</h1>
          <div class="large-12 large-centered columns">
            <form method="GET" action="/search">
              <input type="text" name="query" placeholder="Type the animal your looking for here" {% if keywords %}value="{{ keywords }}"{% endif %}>
            </form>
          </div>
        </div>
      </div>
    </div>
    <br/>
    {% if animals %}
     <div class="row">
      {% for animal in animals %}
      <div class="animal-card large-4 medium-6 small-12 columns">
          <div class="row">
            <div class="large-8 large-offset-2 medium-8 medium-offset-2 small-8 small-offset-2 small-centered large-centered columns end">
              <img class="th" src="{{ animal.picture_url }}"/></br>
              <a class="text-center"  href="{{ animal.url }}">{{ animal.name }}</a>
              <p class="text-justify">{{ animal.summary }}</p>
            </div>
         </div>
        </div>
        {% else %}
        <div class="large-8 large-offset-2 large-centered medium-8 medium-offset-2 small-10 small-offset-1 columns end">
          <h3>Your search did not bring any result back!</h3>
        </div>
      {% endfor %}
     </div>
    {% endif %}

{% endblock content %}

templates/search_home.html
{% extends "base.html" %}

{% block content %}
    <div class="row center-div">
      <div class="large-8 large-offset-2 large-centered columns end">
        <div class="row text-center">
          <h1>Oz Zoo Search!</h1>
          <div class="large-12 large-centered columns">
            <form method="GET" action="/search">
              <input type="text" name="query" placeholder="Type the animal your looking for here" {% if keywords %}value="{{ keywords }}"{% endif %}>
            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}